[package]
name = "FiletoPic-rust"
version = "0.1.0"
authors = ["asm67"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.2"
num-complex = "0.2.4"